---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - .env
    environment:
      - PUID=1206
      - PGID=1100
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${MEDIA}/tv:/tv
      - ${DOWNLOADS}/:/downloads 
    ports:
      - 8989:8989
    restart: always
