---
version: "2.1"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    env_file:
      - .env
    environment:
      - PUID=1205
      - PGID=1100
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/sabnzbd:/config
      - ${DOWNLOADS}/:/downloads
      - ${DOWNLOADS}/incomplete:/incomplete-downloads
    ports:
      - 8080:8080
    restart: always
