---
# Configures a Debian based distro to be a media server
- name: Media Server Setup
  hosts: pve
  gather_facts: false
  tasks:

    - name: Apt update
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600  # Update cache if older than one hour

    - name: Apt upgrade
      become: true
      ansible.builtin.apt:
        upgrade: full
        autoremove: true
        autoclean: true

    - name: Install podman and its requirements
      become: true
      ansible.builtin.apt:
        pkg:
          - podman-compose
          - slirp4netns

    - name: Append line to .bashrc # requirement for rootless podman
      ansible.builtin.lineinfile:
        path: /home/$USER/.bashrc
        line: 'export XDG_RUNTIME_DIR=/run/user/$(id -u)'
        state: present  # Ensures line is present
        insertbefore: EOF  # Add the line at the end of the file
      # notify:
        # - Reload bashrc

  # handlers:

  #   - name: Reload bashrc # reload .bashrc file to instantly apply new settings
  #     ansible.builtin.command: . /home/$USER/.bashrc && tail -n 1 /home/$USER/.bashrc
  #     register: bashrc_last_line
  #     changed_when: "'export XDG_RUNTIME_DIR=/run/user/$(id -u)' in bashrc_last_line.stdout"
